/**
 * `crm completion bash|zsh|fish` — prints a shell completion script
 * generated from the actual command tree, so new subcommands show up
 * without regenerating anything by hand.
 */
import type { Command } from 'commander'

interface Group {
  name: string
  subs: string[]
}

function groups(program: Command): Group[] {
  const out: Group[] = []
  for (const c of program.commands) {
    const subs = c.commands.map((s) => s.name())
    if (subs.length > 0) {
      out.push({ name: c.name(), subs })
    }
  }
  return out
}

function topNames(program: Command): string[] {
  return program.commands.map((c) => c.name())
}

function bashScript(program: Command): string {
  const cases = groups(program)
    .map(
      (g) =>
        `    ${g.name}) REPLY=($(compgen -W "${g.subs.join(' ')}" -- "$cur")); return ;;`,
    )
    .join('\n')
  return `# bash completion for crm — generated by \`crm completion bash\`
_crm() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  case "$prev" in
${cases}
  esac
  REPLY=($(compgen -W "${topNames(program).join(' ')}" -- "$cur"))
}
complete -F _crm crm
`
}

function zshScript(program: Command): string {
  const cases = groups(program)
    .map((g) => `    ${g.name}) subs=(${g.subs.join(' ')}) ;;`)
    .join('\n')
  return `#compdef crm
# zsh completion for crm — generated by \`crm completion zsh\`
_crm() {
  local -a subs
  case "\${words[$CURRENT-1]}" in
${cases}
  esac
  if (( \${#subs[@]} > 0 )); then
    _describe 'crm subcommand' subs
    return
  fi
  subs=(${topNames(program).join(' ')})
  _describe 'crm command' subs
}
`
}

function fishScript(program: Command): string {
  const lines: string[] = [
    '# fish completion for crm — generated by `crm completion fish`',
    'complete -c crm -f',
    `complete -c crm -a "${topNames(program).join(' ')}"`,
  ]
  for (const g of groups(program)) {
    lines.push(
      `function __crm_prev_${g.name}\n  commandline -pt | string match -qr '${g.name}$'\nend`,
      `complete -c crm -n '__crm_prev_${g.name}' -a '${g.subs.join(' ')}'`,
    )
  }
  return `${lines.join('\n')}\n`
}

export function registerCompletionCommand(program: Command): void {
  const cmd = program
    .command('completion')
    .description('Print shell completion scripts')

  cmd
    .command('bash')
    .description('Bash: eval "$(crm completion bash)"')
    .action(() => {
      process.stdout.write(bashScript(program))
    })

  cmd
    .command('zsh')
    .description('Zsh: put on $fpath, or source: crm completion zsh')
    .action(() => {
      process.stdout.write(zshScript(program))
    })

  cmd
    .command('fish')
    .description('Fish: crm completion fish | source')
    .action(() => {
      process.stdout.write(fishScript(program))
    })
}
